version: '3.8'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
