version: '3.5'

services:
  api01: &api
    container_name: api01
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "90MB"

  api02:
    <<: *api
    container_name: api02
    depends_on:
      - api01

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rinha" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
