version: '3.5'

services:
  api01: &api
    container_name: api01
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:3000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - 5435:5432
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
