version: '3.5'

services:
  api01: &api
    container_name: api01
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8081:8080"
    expose:
      - 80
    depends_on:
      db:
        condition: service_healthy

  api02:
    <<: *api
    container_name: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - "9999:9999"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    hostname: localhost
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d rinha" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
